### ISSUE TITLE
NoClassDefFoundError in PhpStorm 8.0.3

### ISSUE THREAD

**Issue by aburban** [davidfuhr/php-plantumlwriter#8]
![zrzut ekranu 2015-08-15 o 23 38 59](https://cloud.githubusercontent.com/assets/6363076/9290970/f1d30c26-43a6-11e5-9410-66660404bd10.png)
![zrzut ekranu 2015-08-15 o 23 41 05](https://cloud.githubusercontent.com/assets/6363076/9290976/25ef50f0-43a7-11e5-9ed2-5d3dd1961dc5.png)

Hi, I have following error, when opening *.puml file in PhpStorm.

23:24:05 NoClassDefFoundError: net/sourceforge/plantuml/BlockUmlBuilder
23:24:25 NoClassDefFoundError: net/sourceforge/plantuml/FileSystem
23:24:27 NoClassDefFoundError: net/sourceforge/plantuml/FileSystem

It works all well however in PhpStorm 9.0.1.

Info:
Id have successfully added plantuml4idea.jar to PhpStorm, also I have Graphiz installed and ./dot setted.
File system is OS X Yosemite 10.10.5

Could you please help me?
Thanks!

`"net/sourceforge/plantuml/BlockUmlBuilder
java.lang.NoClassDefFoundError: net/sourceforge/plantuml/BlockUmlBuilder
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:30)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.renderWithBaseDir(PlantUmlToolWindow.java:212)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.access$1000(PlantUmlToolWindow.java:42)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$RenderWithBaseDirRunnable.run(PlantUmlToolWindow.java:202)
	at org.plantuml.idea.util.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.plantuml.BlockUmlBuilder PluginClassLoader[PlantUML integration, 1.8.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 13 more
"`

**Comment by davidfuhr** [comment]
This tool is not integrated in any way into PHPStorm. Please ask at https://github.com/esteinberg/plantuml4idea for help with the plantuml4idea plugin.
